# Generated by Django 3.1.6 on 2021-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(default='111', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
