# Generated by Django 3.1.6 on 2021-04-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210430_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='transaction_id',
            new_name='pay_id',
        ),
    ]
