# Generated by Django 3.1.6 on 2021-03-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intro',
        ),
    ]
