# Generated by Django 3.1.6 on 2021-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210425_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
