# Generated by Django 3.1.6 on 2021-04-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='detail',
            field=models.TextField(max_length=100),
        ),
    ]
