# Generated by Django 3.1.6 on 2021-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='detail',
            field=models.CharField(default='3 hours of math service', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default='parent2@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
