# Generated by Django 3.1.6 on 2021-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210430_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='detail',
            field=models.CharField(max_length=100),
        ),
    ]
